=== surakshyashrestha/XMLproject/catalog_19033727.dtd
<!ELEMENT musicStore (logo,title,address,address_image,contactNo,contact_image,email,email_image,website,web_image,song)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT address_image (#PCDATA)>
<!ELEMENT contactNo (#PCDATA)>
<!ELEMENT contact_image (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT email_image (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT web_image (#PCDATA)>
<!ELEMENT song (songs+)>
<!ELEMENT songs (coverPhoto,songDescription)>
<!ELEMENT coverPhoto (#PCDATA)>
<!ELEMENT songDescription (details1,details2,details3?,details4,details5,details6,details7?,details8?,details9?,details10?,details11?)>
<!ELEMENT details1 (songtitle,songname)>
<!ELEMENT songtitle (#PCDATA)>
<!ELEMENT songname (#PCDATA)>
<!ELEMENT details2 (songtitle,Artist)>
<!ELEMENT Artist (#PCDATA)>
<!ELEMENT details3 (songtitle,artist)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT details4 (songtitle,Genre)>
<!ELEMENT Genre (#PCDATA)>
<!ELEMENT details5 (songtitle,Releasedate)>
<!ELEMENT Releasedate (#PCDATA)>
<!ELEMENT details6 (songtitle,timeLength)>
<!ELEMENT timeLength (#PCDATA)>
<!ELEMENT details7 (songtitle,Album)>
<!ELEMENT Album (#PCDATA)>
<!ELEMENT details8 (songtitle,Producer)>
<!ELEMENT Producer (#PCDATA)>
<!ELEMENT details9 (songtitle,Songwriter)>
<!ELEMENT Songwriter (#PCDATA)>
<!ELEMENT details10 (songtitle,Nominations)>
<!ELEMENT Nominations (#PCDATA)>
<!ELEMENT details11 (songtitle,Awards)>
<!ELEMENT Awards (#PCDATA)>
<!ATTLIST songs id CDATA #IMPLIED>
<!ATTLIST coverPhoto song CDATA #IMPLIED>
<!ATTLIST Album album CDATA #IMPLIED>
<!ATTLIST Producer producer CDATA #IMPLIED>
<!ATTLIST artist name CDATA #IMPLIED>

=== surakshyashrestha/XMLproject/catalog_19033727.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="catalog_19033727.css"?>
<!-- <!DOCTYPE musicStore SYSTEM "catalog_19033727.dtd"> -->
<musicStore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 		xsi:noNamespaceSchemaLocation="catalog_19033727.xsd">
    <logo></logo>
    <title> Musical Cartoon</title>
    <address>Basundhara, Kathmandu</address>
    <address_image></address_image>
    <contactNo>+977-9867849736</contactNo>
    <contact_image></contact_image>
    <email>surakshyashrestha024@gmail.com</email>
    <email_image></email_image>
    <website>www.cartoonmusicstore.com</website>
    <web_image></web_image>
    <song>
       <songs id="song1">
            <coverPhoto song="cover1"></coverPhoto>
            <songDescription>
                <details1>
                    <songtitle>
						Song Name:
					</songtitle>
                    <songname>
						Dynamite
					</songname>
                </details1>
                <details2>
                    <songtitle>
						Artist:
					</songtitle>
                    <Artist>
						BTS
					</Artist>
                </details2>
                <details4>
                    <songtitle>
						Genre:
					</songtitle>
                    <Genre>
						Disco, Pop
					</Genre>
                </details4>
                <details5>
                    <songtitle>
						Release Date:
					</songtitle>
                    <Releasedate>
						August 21, 2020
					</Releasedate>
                </details5>
                <details6>
                    <songtitle>
						Time Length:
					</songtitle>
                    <timeLength>
						3mins 19seconds
					</timeLength>
                </details6>
                <details8>
                    <songtitle>
						Producer:
					</songtitle>
                    <Producer producer="producerName">
						David Stewart
					</Producer>
                </details8>
                <details10>
                    <songtitle>
						Nominations:
					</songtitle>
                    <Nominations>
						Golden Disc Award Song Division, Mnet Asian Music Award for the song of the year,more
					</Nominations>
                </details10>
                <details11>
                    <songtitle>
						Awards:
					</songtitle>
                    <Awards>
						Grammy Award for Best Pop Duo/Group performance,Golden Disc Award Song Division,more
					</Awards>
                </details11>
            </songDescription>
        </songs>
        <songs id="song2">
            <coverPhoto song="cover2"></coverPhoto>
            <songDescription>
                <details1>
                    <songtitle>Song Name:</songtitle>
                    <songname>Icecream</songname>
                </details1>
                <details2>
                    <songtitle>Artist:</songtitle>
                    <Artist>Blackpink</Artist>
                </details2>
                <details3>
                    <songtitle>Featured artist:</songtitle>
                    <artist name="S1">Selena Gomez</artist>
                </details3>
                <details4>
                    <songtitle>Genre:</songtitle>
                    <Genre>Bubblegum pop,trap,pop,electropop</Genre>
                </details4>
                <details5>
                    <songtitle>Release Date:</songtitle>
                    <Releasedate>August 28,2020</Releasedate>
                </details5>
                <details6>
                    <songtitle>Time Length:</songtitle>
                    <timeLength>2mins 56seconds</timeLength>
                </details6>
                <details7>
                    <songtitle>Album:</songtitle>
                    <Album album="A10">The Album</Album>
                </details7>
                <details10>
                    <songtitle>Nominations:</songtitle>
                    <Nominations>Kids choice Award for Favourite Collaboration
					</Nominations>
                </details10>
            </songDescription>
        </songs>
        <songs id="song3">
            <coverPhoto song="cover3"></coverPhoto>
            <songDescription>
                <details1>
                    <songtitle>
						Song Name:
					</songtitle>
                    <songname>
						ME!
					</songname>
                </details1>
                <details2>
                    <songtitle>
						Artist:
					</songtitle>
                    <Artist>
						Taylor Swift
					</Artist>
                </details2>
                <details4>
                    <songtitle>
						Genre:
					</songtitle>
                    <Genre>
						Bubblegum music, Pop
					</Genre>
                </details4>
                <details5>
                    <songtitle>
						Release Date:
					</songtitle>
                    <Releasedate>
						August 26, 2019
					</Releasedate>
                </details5>
                <details6>
                    <songtitle>
						Time Length:
					</songtitle>
                    <timeLength>
						3mins 13seconds
					</timeLength>
                </details6>
                <details7>
                    <songtitle>
						Album:
					</songtitle>
                    <Album album="A1">
						Lover
					</Album>
                </details7>
                <details10>
                    <songtitle>
						Nominations:
					</songtitle>
                    <Nominations>
						MTV Video Music Award for Best Cinematography,more
					</Nominations>
                </details10>
                <details11>
                    <songtitle>
						Awards:
					</songtitle>
                    <Awards>
						MTV Video Music Award for Best Visual Effects, MTV Europe Music Award for Best Video
					</Awards>
                </details11>
            </songDescription>
        </songs>
        <songs id="song4">
            <coverPhoto song="cover4"></coverPhoto>
            <songDescription>
                <details1>
                    <songtitle>
						Song Name:
					</songtitle>
                    <songname>
						Agar Tum Saath Ho
					</songname>
                </details1>
                <details2>
                    <songtitle>
						Artist:
					</songtitle>
                    <Artist>
						Arjit Singh,Alka Yagnik
					</Artist>
                </details2>
                <details4>
                    <songtitle>
						Genre:
					</songtitle>
                    <Genre>
						Filmi
					</Genre>
                </details4>
                <details5>
                    <songtitle>
						Release Date:
					</songtitle>
                    <Releasedate>
						16 October 2015
					</Releasedate>
                </details5>
                <details6>
                    <songtitle>
						Time Length:
					</songtitle>
                    <timeLength>
						46 seconds
					</timeLength>
                </details6>
                <details8>
                    <songtitle>
						Producer:
					</songtitle>
                    <Producer producer="P1">
						A.R.Rahman
					</Producer>
                </details8>
                <details10>
                    <songtitle>
						Nominations:
					</songtitle>
                    <Nominations>
						Mirchi Music Awards for Listener's Choice Song of the year,more
					</Nominations>
                </details10>
                <details11>
                    <songtitle>
						Awards:
					</songtitle>
                    <Awards>
						Mirchi Music Award for Listener's Choice Song of the Year,Filmfare Award for Best Lyricist,more
					</Awards>
                </details11>
            </songDescription>
        </songs>
        <songs id="song5">
            <coverPhoto song="cover5"></coverPhoto>
            <songDescription>
                <details1>
                    <songtitle>
						Song Name:
					</songtitle>
                    <songname>
						Perfect
					</songname>
                </details1>
                <details2>
                    <songtitle>
						Artist:
					</songtitle>
                    <Artist>
						Ed Sheeran
					</Artist>
                </details2>
                <details4>
                    <songtitle>
						Genre:
					</songtitle>
                    <Genre>
						Pop
					</Genre>
                </details4>
                <details5>
                    <songtitle>
						Release Date:
					</songtitle>
                    <Releasedate>
						26 September 2017
					</Releasedate>
                </details5>
                <details6>
                    <songtitle>
						Time Length:
					</songtitle>
                    <timeLength>
						4min 23seconds
					</timeLength>
                </details6>
                <details7>
                    <songtitle>
						Album:
					</songtitle>
                    <Album album="A3">
						Divide
					</Album>
                </details7>
                <details10>
                    <songtitle>
						Nominations:
					</songtitle>
                    <Nominations>
						MTV Video Music Award for Best Pop Video,MTV Video Music Award for Best Direction,more
					</Nominations>
                </details10>
                <details11>
                    <songtitle>
						Awards:
					</songtitle>
                    <Awards>
						Teen Choice Award for Single:MaleArtist,Radio Disney Music Award for Best Crush Song,MuchMusic Video Award for Single of the Year
					</Awards>
                </details11>
            </songDescription>
        </songs>
        <songs id="song6">
            <coverPhoto song="cover6"></coverPhoto>
            <songDescription>
                <details1>
